// <auto-generated />
namespace BigSchool_TranVanNghia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class khoitao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(khoitao));
        
        string IMigrationMetadata.Id
        {
            get { return "202303090202153_khoi tao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
